name: BhashaMind CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-backend:
    name: Python Backend - FastAPI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-python
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest

      - name: Lint (ruff)
        run: ruff check --fix app tests

      - name: Run Tests
        run: pytest tests

  java-gateway:
    name: Java API Gateway - Spring Boot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-java
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Test (Maven)
        run: |
          ./mvnw clean install -DskipTests=false
